apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  default.conf: |
    server {
        listen       5432 default_server;
        server_name  _;

        default_type text/plain;

        location / {
            return 200 '$hostname\n';
        }
    }