apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://eats_user:secret_password@db-service:5432/My_Eats"
  POSTGRES_USER: "eats_user"
  POSTGRES_PASSWORD: "secret_password"
  POSTGRES_DB: "My_Eats"
